### ISSUE TITLE
Produced layer do not work with other layers

### ISSUE THREAD

**Issue by pchome** [Joshua-Ashton/vkroots#2] opened 2022-05-07 15:04 UTC
##### Observed behavior:
* It work if it is the only loaded layer
* It hang if it was loaded first
* It work incorrectly if it was loaded last

_(if only I don't messed with load order)_

##### Incorrect variant note
I created a layer sample which modifying device name, so `vkcube` prints this modified device name in terminal. But with MESA layer loaded only MESA hud shows modified device name, vkcube prints original device name.
 
##### Test script sample
```bash
export VK_INSTANCE_LAYERS="VK_LAYER_MESA_overlay:VK_LAYER_frog_sample" #OK
export VK_INSTANCE_LAYERS="VK_LAYER_frog_sample:VK_LAYER_MESA_overlay" #KO
export VK_ADD_LAYER_PATH="."
export LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}"
vkcube
```
Note: replace `VK_LAYER_MESA_overlay` with `VK_LAYER_KHRONOS_validation` or other layer available in system.

**Comment by misyltoad** [comment] 2022-05-07 16:42
Thanks, I think I know the cause, will check when I can.

**Comment by misyltoad** [comment] 2022-05-09 02:33
Should be fixed now.

**Closed as completed by misyltoad** 2022-05-09 02:33 UTC

**Comment by pchome** [comment] 2022-05-10 10:49
Incorrect variant is still a thing.
I'm not sure if this is correct fix, but it kind of works if I remove wrappers for `Get*ProcAddr`, e.g.
```cpp
    //constexpr bool HasGetDeviceProcAddr = requires(const DeviceOverrides& t) { &DeviceOverrides::GetDeviceProcAddr; };
    //if constexpr (HasGetDeviceProcAddr) {
      if (!std::strcmp("vkGetDeviceProcAddr", name))
        //return (PFN_vkVoidFunction) &wrap_GetDeviceProcAddr<InstanceOverrides, PhysicalDeviceOverrides, DeviceOverrides>;
        if (!std::is_base_of<NoOverrides, DeviceOverrides>::value)
          return (PFN_vkVoidFunction) &GetDeviceProcAddr<InstanceOverrides, PhysicalDeviceOverrides, DeviceOverrides>;
    //}
``` 
Test
```bash
export VK_INSTANCE_LAYERS="VK_LAYER_frog_sample"                       # PRE: 2 frogs / POST: 2 frogs
export VK_INSTANCE_LAYERS="VK_LAYER_frog_sample:VK_LAYER_MESA_overlay" # PRE: 2 frogs / POST: 2 frogs
export VK_INSTANCE_LAYERS="VK_LAYER_MESA_overlay:VK_LAYER_frog_sample" # PRE: 1 frog  / POST: 3 frogs
```

**Comment by misyltoad** [comment] 2022-05-10 12:55
Works on my machine! Can you send a backtrace?

**Comment by pchome** [comment] 2022-05-10 14:30
I mean layer not hangs anymore, but "observed behavior \#3" still there.
"\# frogs" means number of printed messages ("frogtastically beautiful") in terminal (pre/post modification).

Maybe related to:
https://github.com/DadSchoorse/vkBasalt/commit/a85f91e92b245f97d6e9847af1d5e4839ae3c00f
https://github.com/mesa3d/mesa/commit/fff77e4b434a4989e6c54ab7ef8d1aa22fe81b3a

Please give me console command example to generate any debug information.

**Comment by pchome** [comment] 2022-05-11 22:48
I recreated vkroots sample layer using Vulkan Layer Factory and then again using my own layer code. Both variants prints three messages when `VK_LAYER_MESA_overlay` listed first. Not that it proves something, just to double-check myself.

P.S. I copy/pasted vkroots sample layer to make a duplicate, then used both at the same time  -- segfault on original version, four messages on modified version.
